### ISSUE TITLE
No dialogs appear on iOS/MacCatalyst using v1.5.2

### ISSUE THREAD

**Issue by joemather** [Alex-Dobrynin/Controls.UserDialogs.Maui#11]
v1.5.1 works great.  But when I upgrade to v1.5.2, no dialogs (alert, confirm, loading, etc) appear on iOS or MacCatalyst.

Simple example that reproduces the problem with an Alert dialog:

1. Create a brand new .NET 8 Maui app in JetBrains Rider.

2. Add Controls.UserDialogs.Maui **v1.5.1** package from Nuget.

3. Initialize UserDialogs in `MauiProgram`: 
```
    var builder = MauiApp.CreateBuilder();
    builder
        .UseMauiApp<App>()
        .UseUserDialogs(() => { })   // Initialize UserDialogs here
        .ConfigureFonts(fonts =>
        {
            fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
            fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
        });
```

4. Add a trivial dialog to the button handler in `MainPage.xaml.cs`:
```
    private void OnCounterClicked(object sender, EventArgs e)
    {
        count++;

        if (count == 1)
            CounterBtn.Text = $"Clicked {count} time";
        else
            CounterBtn.Text = $"Clicked {count} times";

        SemanticScreenReader.Announce(CounterBtn.Text);

        // Exercise UserDialogs here.  Simple example to demonstrate the problem.
        Controls.UserDialogs.Maui.UserDialogs.Instance.Alert("hello!", "test dialog");
    }
```

5. Run app and press the button on iOS sim, iOS device, MacCatalyst and Android device.  Works great!  Alert appears on all platforms. 

6. Upgrade to Controls.UserDialogs.Maui **v1.5.2** package from Nuget.  Delete bin and obj.  Rebuild.

7.  Run app and press the button on iOS sim, iOS device, MacCatalyst and Android device. **Alert only appears on Android device.  Nothing appears on iOS sim, iOS device or MacCatalyst**.

Same behavior with confirm and loading dialogs.  Nothing appears on iOS/MacCatalyst with v1.5.2.  I didn't test other types of dialogs (e.g. action sheets).

When I downgrade to Controls.UserDialogs.Maui v1.5.1 or v1.5.0, dialogs start working again on iOS/MacCatalyst.

It's not a package upgrade issue because if I start "clean" with a brand new .NET 8 Maui app and Controls.UserDialogs.Maui v1.5.2, the dialogs still do not appear on iOS/MacCatalyst.

It seems something is broken in v1.5.2.  The workaround is to stick with v1.5.1.

**Comment by Bruno2049** [comment]
I checked this issue today with version 1.5.3 and the dialogs still doesn't show up.

**Comment by Alex-Dobrynin** [comment]
Hello! Did you try to run the Sample project from this repo? is there the same?

**Comment by Alex-Dobrynin** [comment]
Also, I'm using the latest nuget package version in my projects. on ios and mac as well as on android works perfect

**Comment by joemather** [comment]
I retested my app with v1.5.3.  Same problem -- no dialogs appear on my iOS device (iPhone 15 Pro / iOS 17.3.1).  I didn't retest iOS simulator, MacCatalyst or Android.

Next I downloaded the Sample app from this repo.  The Sample app uses a project reference, not the Nuget package:
```
	<ItemGroup>
	  <ProjectReference Include="..\Controls.UserDialogs.Maui\Controls.UserDialogs.Maui.csproj" />
	</ItemGroup>
```

I deleted that project reference from the Sample app and replaced it with **v1.5.1 from Nuget**:
```
	<ItemGroup>
		<PackageReference Include="Controls.UserDialogs.Maui" Version="1.5.1" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
	</ItemGroup>
```

Deleted bin/obj, rebuilt, and installed the Sample app on my iOS device (iPhone 15 Pro / iOS 17.3.1).  Dialogs of all kind (Alert, Confirm, Bottom Action Sheet, Image HUD, Toast) worked great.  So far so good with v1.5.1.

Next, I upgraded the Sample app to **v1.5.3 from Nuget**:
```
	<ItemGroup>
		<PackageReference Include="Controls.UserDialogs.Maui" Version="1.5.3" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
	</ItemGroup>
```

Deleted bin/obj, rebuilt, and installed the Sample app on my iOS device (iPhone 15 Pro / iOS 17.3.1).   **No dialogs of any kind appear**.  Nothing happens when the buttons are tapped, but if you keep tapping them, eventually the Sample app crashes.

So the same problem exists in v1.5.3 and it's reproducible with the Sample app. The workaround is to stick with v1.5.1.

**Comment by Alex-Dobrynin** [comment]
@joemather  did the same, works perfect. please provide test project (.zip) i will double check it.

**Comment by Bruno2049** [comment]
Sorry for the eary comment. I update my workloads for MAUI and after testing again with version 1.5.3 nuget package, I can confirm that dialogs are working well.

**Comment by joemather** [comment]
@Bruno2049 - What are your Maui workloads?  Here are mine:

```
% dotnet workload list 

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-maccatalyst           8.0.3/8.0.100          SDK 8.0.100        
maui-ios                   8.0.3/8.0.100          SDK 8.0.100        
maui-android               8.0.3/8.0.100          SDK 8.0.100        
ios                        17.0.8490/8.0.100      SDK 8.0.100        
maccatalyst                17.0.8490/8.0.100      SDK 8.0.100        
maui                       8.0.3/8.0.100          SDK 8.0.100        
android                    34.0.52/8.0.100        SDK 8.0.100        
wasm-tools-net7            8.0.1/8.0.100          SDK 8.0.100   
```

**Comment by joemather** [comment]
@Alex-Dobrynin - Project attached.  Only difference is the .csproj file.  Thanks for your help!

[Sample.zip](https://github.com/Alex-Dobrynin/Controls.UserDialogs.Maui/files/14422564/Sample.zip)

**Comment by Alex-Dobrynin** [comment]
@joemather works like a charm. try to update maui workload as @Bruno2049 mentioned

**Comment by joemather** [comment]
Updated all workloads and now v1.5.3 works! 

Thank you, @Alex-Dobrynin and @Bruno2049 !

```
% dotnet workload list

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-maccatalyst           8.0.6/8.0.100          SDK 8.0.100        
maui-ios                   8.0.6/8.0.100          SDK 8.0.100        
maui-android               8.0.6/8.0.100          SDK 8.0.100        
ios                        17.2.8022/8.0.100      SDK 8.0.100        
maccatalyst                17.2.8022/8.0.100      SDK 8.0.100        
maui                       8.0.6/8.0.100          SDK 8.0.100        
android                    34.0.79/8.0.100        SDK 8.0.100        
wasm-tools-net7            8.0.2/8.0.100          SDK 8.0.100        
```
