### ISSUE TITLE
UI is not blocking controls

### ISSUE THREAD

**Issue by andreptcosta** [Alex-Dobrynin/Controls.UserDialogs.Maui#16]
**Describe the bug**
I'm noticing that when the dialog Loading is open, I can still touch the controls behind, causing some bugs in my app. Is there any way to lock the UI while user dialog is being displayed?

**To Reproduce**
1. Launch `UserDialogs.Instance.ShowLoading(message, MaskType.Black);`
2. Try click on controls from page
3. Page controls are accessible, where they should be blocked by the user dialog UI

**Did you run Sample project from this repo, is there the same?**
yes, the result is the same.

**Smartphone (please complete the following information):**
 - Device: any
 - OS: Android

**Did you found a workaround?**
Not

**Comment by Alex-Dobrynin** [comment]
Thanks. Yes, can confirm this. But, unfortunately, I don't have enough time to fix this, and will do when I have time. If this is urgent for you, you may create a PR with the fix, or wait until I do this.

**Comment by andreptcosta** [comment]
@Alex-Dobrynin I found the problem and applied the solution. Can I create a pull request? Can you grant me permission?

**Comment by andreptcosta** [comment]
@Alex-Dobrynin I got it the problem and fix. Can I create a pull request? Can you grant me permission to create a branch?

**Comment by Alex-Dobrynin** [comment]
> @Alex-Dobrynin I got it the problem and fix. Can I create a pull request? Can you grant me permission to create a branch?

just fork this repo, do the fix in your fork, and the create a pr into this repo master branch

**Comment by kberawala** [comment]
is this launched ?

**Comment by Alex-Dobrynin** [comment]
@kberawala what do you mean by launched?
