### ISSUE TITLE
[iOS] Unrecognized non-english characters

### ISSUE THREAD

**Issue by FranRDev** [Alex-Dobrynin/Controls.UserDialogs.Maui#18]
**Description:**
On Android works great, but on iOS the dialogs don't recognize non-english characters.

**Software:**
 - macOS Sonoma 14.5
 - Visual Studio for Mac 17.6.12 (build 410)
 - Microsoft.Maui.* 8.0.40
 - Controls.UserDialogs.Maui 1.5.4
 - iPhone XS Max > iOS 17.5
 
 **Images:**
<img src="https://github.com/Alex-Dobrynin/Controls.UserDialogs.Maui/assets/36072624/5feaf7d4-efdb-4260-8a4f-91b46965dbeb" width="250">
<img src="https://github.com/Alex-Dobrynin/Controls.UserDialogs.Maui/assets/36072624/7bca2d1f-d813-43b4-9fa9-8688bc80b1bf" width="250">

**Comment by Alex-Dobrynin** [comment]
can you write here the string you are using?

**Comment by FranRDev** [comment]
> can you write here the string you are using?

_"Cargando día..."_ and _"¿Desea solicitar un fichaje olvidado a las 12:00? Se cotejará con el paso por los tornos y e notificará a su responsable."_.

**Comment by Alex-Dobrynin** [comment]
can you try the sample project from this repo, is there the same?

**Comment by FranRDev** [comment]
> can you try the sample project from this repo, is there the same?

With the sample project don't happend, works fine.

**Comment by Alex-Dobrynin** [comment]
Then look for it in your project. Sorry, but I'm closing this issue. Check your localisation files, or maybe project settings
