### ISSUE TITLE
UserDialogs.Instance.ShowSnackbar with SnackbarConfig param error

### ISSUE THREAD

**Issue by ntbao17** [Alex-Dobrynin/Controls.UserDialogs.Maui#19]
UserDialogs.Instance.ShowSnackbar(new SnackbarConfig()
{
    Message = $"content",
    Icon = "accept_notification_24dp.png",
    Duration = TimeSpan.FromSeconds(5),
    Position = ToastPosition.Top,
    BackgroundColor = Color.FromArgb(GLOBAL.GlobalProperties.ColorModifierForApp.AppColor.PrimaryColor),
    MessageColor = Color.FromArgb(GLOBAL.GlobalProperties.ColorModifierForApp.AppColor.TextColorPrimary),
    Action = async (type) =>
    {
       
    }
});

I used this method to display the error on Android and iOS, please help me check again!

Android 
Java.Lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
[DOTNET]    at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 20830
[DOTNET]    at Java.Interop.JniPeerMembers.JniInstanceMethods.FinishCreateInstance(String constructorSignature, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs:line 174
[DOTNET]    at Android.Text.SpannableString..ctor(String source) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Text.SpannableString.cs:line 85
[DOTNET]    at Controls.UserDialogs.Maui.SnackbarBuilder.SetupSnackbarAction(Snackbar snackbar)
[DOTNET]    at Controls.UserDialogs.Maui.SnackbarBuilder.Build()
[DOTNET]    at Controls.UserDialogs.Maui.UserDialogsImplementation.<>c__DisplayClass15_0.<ShowSnackbar>b__0()
[DOTNET]    at Controls.UserDialogs.Maui.Extensions.<>c__DisplayClass2_0.<SafeRunOnUi>b__0()
[DOTNET]   --- End of managed Java.Lang.NullPointerException stack trace ---
[DOTNET] java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
[DOTNET] 	at android.text.SpannableString.<init>(SpannableString.java:34)
[DOTNET] 	at android.text.SpannableString.<init>(SpannableString.java:43)
[DOTNET] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[DOTNET] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
[DOTNET] 	at android.app.Activity.runOnUiThread(Activity.java:7355)
[DOTNET] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[DOTNET] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
[DOTNET] 	at android.os.Handler.handleCallback(Handler.java:942)
[DOTNET] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[DOTNET] 	at android.os.Looper.loopOnce(Looper.java:201)
[DOTNET] 	at android.os.Looper.loop(Looper.java:288)
[DOTNET] 	at android.app.ActivityThread.main(ActivityThread.java:8057)
[DOTNET] 	at java.lang.reflect.Method.invoke(Native Method)
[DOTNET] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703)
[DOTNET] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
[DOTNET] 
[DOTNET]   --- End of managed Java.Lang.NullPointerException stack trace ---
[DOTNET] java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
[DOTNET] 	at android.text.SpannableString.<init>(SpannableString.java:34)
[DOTNET] 	at android.text.SpannableString.<init>(SpannableString.java:43)
[DOTNET] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[DOTNET] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
[DOTNET] 	at android.app.Activity.runOnUiThread(Activity.java:7355)
[DOTNET] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[DOTNET] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
[DOTNET] 	at android.os.Handler.handleCallback(Handler.java:942)
[DOTNET] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[DOTNET] 	at android.os.Looper.loopOnce(Looper.java:201)
[DOTNET] 	at android.os.Looper.loop(Looper.java:288)
[DOTNET] 	at android.app.ActivityThread.main(ActivityThread.java:8057)
[DOTNET] 	at java.lang.reflect.Method.invoke(Native Method)
[DOTNET] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703)
[DOTNET] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

iOS

System.ArgumentNullException: Value cannot be null. (Parameter 'str')
   at ObjCRuntime.ThrowHelper.ThrowArgumentNullException(String argumentName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/ThrowHelper.cs:line 28
2024-05-24 14:50:30.207 Clubsync[4273:1828698]    at Foundation.NSMutableAttributedString..ctor(String str, NSDictionary attributes) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/Foundation/NSMutableAttributedString.g.cs:line 115
2024-05-24 14:50:30.207 Clubsync[4273:1828698]    at Foundation.NSMutableAttributedString..ctor(String str, UIFont font, UIColor foregroundColor, UIColor backgroundColor, UIColor strokeColor, NSParagraphStyle paragraphStyle, NSLigatureType ligatures, Single kerning, NSUnderlineStyle underlineStyle, NSShadow shadow, Single strokeWidth, NSUnderlineStyle strikethroughStyle) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSMutableAttributedString.cs:line 97
   at Controls.UserDialogs.Maui.Snackbar.GetActionButton()
   at Controls.UserDialogs.Maui.Snackbar.GetAction()
2024-05-24 14:50:30.207 Clubsync[4273:1828698]    at Controls.UserDialogs.Maui.Snackbar.SetupSnackBar()
   at Controls.UserDialogs.Maui.Snackbar.Show()
   at Controls.UserDialogs.Maui.UserDialogsImplementation.<>c__DisplayClass11_0.<ShowSnackbar>b__0()
2024-05-24 14:50:30.207 Clubsync[4273:1828698]    at Controls.UserDialogs.Maui.Extensions.<>c__DisplayClass0_0.<SafeInvokeOnMainThread>b__0()

**Comment by Alex-Dobrynin** [comment]
Hello. Have you tried your case in Sample project from this repo?
