### ISSUE TITLE
Progress dialog doesn't display the text correctly if the device language is Hebrew

### ISSUE THREAD

**Issue by Jones-Abramoff** [Alex-Dobrynin/Controls.UserDialogs.Maui#28]
**Describe the bug**
If the device language is Hebrew, the text is not shown correctly, it truncates or even doesn't show the content as expected.
If the text to be displayed is short, no text is displayed.

**To Reproduce**
Run the sample in Hebrew. It will truncate part.
The make the texts shorter, and it will not display anything.

**Did you run Sample project from this repo, is there the same?**
It fails

**Desktop (please complete the following information):**
windows 11/64 bits

**Smartphone (please complete the following information):**
Samsung M54 with Android 14

**Did you found a workaround?**
No

**Comment by Alex-Dobrynin** [comment]
I'm sorry, but I'm not using hebrew in my life. If you want me to check and find solution how to fix this, you should give me the reproduction project with all of your cases

**Comment by Jones-Abramoff** [comment]
Hi,
Thanks for your prompt reply.
Change your device to Hebrew ( עברית) remembering the icons/position to switch it back to your native language.
Start the sample project and click on the Progress button.
You will see that it cut part of the text.
Make the text shorter and it will show no text at all.

**Comment by Alex-Dobrynin** [comment]
The thing is that it does not support RTL. And second, My package is using AndHUD package to show progress and loading, so the bug is there, you may try to go there and submit a ticket there.

**Comment by Alex-Dobrynin** [comment]
implemented in 1.7.0

**Comment by Jones-Abramoff** [comment]
Thanks a lot.
I'm really grateful.
