### ISSUE TITLE
Add missing support for plain .NET 7.0 target

### ISSUE THREAD

**Issue by ewerspej** [Alex-Dobrynin/Controls.UserDialogs.Maui#4]
Currently, Controls.UserDialogs.Maui doesn't support plain .NET targets such as `net7.0`, which prevents direct support for unit test projects.

A workaround would be to create another abstraction on top of the `IUserDialogs` interface to hide the dependency. However, this is not ideal and shouldn't be required.

Instead, the library should have a `net7.0` target set and provide a null object implementation. 

I can provide a PR for this myself.

**Comment by veringm** [comment]
Tried to branch in order to make a PR with an updated readme.md file - for that file to reflect the support of .NET7. But "Permission Denied".
