### ISSUE TITLE
Loading - Erroring "Is your activity running"

### ISSUE THREAD

**Issue by Mysame** [Alex-Dobrynin/Controls.UserDialogs.Maui#6]
![image](https://github.com/Alex-Dobrynin/Controls.UserDialogs.Maui/assets/1966231/4629be5f-a5d7-4c7b-ad2c-eb6a6fa4ecf3)

Toasts, confirm, alert all seem to work, but Loading gives the above error.
Still on version 1.4.0, haven't updated to net8, but as far as I can see there's no functional differences between versions.

```
        public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder
                .UseMauiApp<App>()
                .UseUserDialogs(true, () =>
                {
                })
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                    fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
                });

            return builder.Build();
        }
```

Testing locally on an Android device, the above code firing the events happens in a button Click event

**Comment by Alex-Dobrynin** [comment]
Very little info, please add repro project

**Comment by Alex-Dobrynin** [comment]
Closing as you didn't provide repro project. When you provide repro project, I will reopen it

**Comment by smjllm** [comment]
In Android version <= 10 is needed to call UserDialogs.Instance.HideHud() when the app go to background because is the only method to clean the activity attached th the hud dialog and force to recreate it.
