### ISSUE TITLE
Not working on Android 14

### ISSUE THREAD

**Issue by erossini** [Alex-Dobrynin/Controls.UserDialogs.Maui#8]
Hi,
I was following the setup of the component in my `MAUI` application with `NET8`. I inject the `IUserDialogs` in the `ContentPage` or in the ViewModel. When I call `_userDialogs.ShowLoading`, the dialog popup is not displayed. In the _Output_ window of Visual Studio, I can see some issues with Android.

Your demo is working. Have you experienced something like that before?

Thank you in advance,
Enrico

**Comment by Alex-Dobrynin** [comment]
No, I haven't. Could you provide a test project here?

**Comment by Alex-Dobrynin** [comment]
Closing as you didn't provide repro project. When you provide repro project, I will reopen it
