### ISSUE TITLE
Missing prompt configuration 

### ISSUE THREAD

**Issue by Arieldelossantos** [Alex-Dobrynin/Controls.UserDialogs.Maui#9]
I'm upgrading from Forms to Maui and i'm having issues upgrading PromptAsync, DatePromptConfig and PromptConfig.

i've also noted some missing features:
- Date
- Prompt
- Time

Any idea on when this is going to be migrated too? Thanks

**Comment by Alex-Dobrynin** [comment]
There is no such dialogs as you described. This is not [Acr.UserDialogs](https://github.com/aritchie/userdialogs).
If you need such popups, you can use this library [MPowerKit.Popups](https://github.com/MPowerKit/Popups) and create custom dialogs for your needs.
Or you can make a PR with this implementations.

**Comment by buchatsky** [comment]
Prompts can currently be achieved with Page.DisplayPromptAsync(), and the typed input will be available in .Net 9.0
